### ISSUE TITLE
为什么你可以构建成功

### ISSUE THREAD

**Issue by sumingyd** [ThrRip/OpenCore-Install-Guide#15]
我一直想尝试自己构建一个翻译。老是不成功。我fork原始的之后直接改，稍微一变动，GitHub自带的那个自动流就编译失败。
我试着把他拉取到本地。没改的情况下dev就不成功。   也不知道哪的问题

**Comment by ThrRip** [comment]
我去你的 fork 看了一下，是把生成的 HTML push 到 `gh-pages` 分支时出错。你可能没有在 repo 设置中指定需要的 `ACCESS_TOKEN` secret。

具体步骤如下：
1. 前往 GitHub [Settings / Developer settings / Personal access tokens](https://github.com/settings/tokens)
2. 点击 **Generate new token** 按钮，在 **Repository access** 一栏中选择 **Only select repositories** 并选择你的 **_OpenCore Install Guide_** repo
3. 点击最下方的 **Generate token**
4. 复制生成的 token，进入 **repo 设置 / Security / Secrets and variables / Actions** (`github.com/<namespace>/<repo>/settings/secrets/actions`)
5. 点击 **New repository secret**，**Name** 填写 `ACCESS_TOKEN`，在 **Secret** 处粘贴复制的 token，点击 **Add secret**

前往 repo Actions 页面并在左侧选择正确的 workflow，你的 repo 中应为 _Build/Test/Deploy_，点击 _This workflow has a ... event trigger_ 右侧的 **Run workflow**，选择 `master` 分支并尝试再次运行 workflow。

<details>
  <summary>碎碎念</summary>
  GitHub 进行了大量更新后，这些功能甚至比两年前我刚开始学习使用 Git 和 GitHub，开始翻译 OpenCore Install Guide 的时候还要复杂。
</details>

**Comment by sumingyd** [comment]
> 

感谢感谢，实在太感谢了，年后回家我再试试。之前百度过太多次，也没研究出来怎么搞。

**Comment by sumingyd** [comment]
> 我去你的 fork 看了一下，是把生成的 HTML push 到 分支时出错。你可能没有在 repo 设置中指定需要的 secret。`gh-pages``ACCESS_TOKEN`
> 
> 具体步骤如下：
> 
> 1. 前往 GitHub 设置 [/ 开发人员设置 / 个人访问令牌](https://github.com/settings/tokens)
> 2. 点击 **生成新令牌** 按钮，在 **Repository Access** 一栏中选择 **仅选择存储库** 并选择你的 **_OpenCore 安装指南_** repo
> 3. 点击最下方的 **生成令牌**
> 4. 复制生成的 token，进入 **repo 设置 / 安全性 / 机密和变量 / 操作** (`github.com/<namespace>/<repo>/settings/secrets/actions`)
> 5. 点击 **New repository** secret，**Name** 填写 ，在 **Secret** 处粘贴复制的 token，点击 **Add secret**`ACCESS_TOKEN`
> 
> 前往 repo Actions 页面并在左侧选择正确的 工作流，你的 repo 中应为 _Build/Test/Deploy_，点击 _事件触发器_ 右侧的 **Run workflow**，选择 分支并尝试再次运行 工作流。`master`
> 
> 碎碎念

试了下，一改内容他自动构建还是错误。自己手动点构建没问题。但内容并不是按修改过后的内容构建的。

**Comment by ThrRip** [comment]
> 试了下，一改内容他自动构建还是错误。自己手动点构建没问题。但内容并不是按修改过后的内容构建的。

是因为 workflow 中的 `lint` job 由于文档内的格式问题而失败。在该 job 每次执行的输出中都包含可以直接应用以解决问题的 Git 补丁。

**Comment by sumingyd** [comment]
> > 试了下，一改内容他自动构建还是错误。自己手动点构建没问题。但内容并不是按修改过后的内容构建的。
> 
> 是因为 workflow 中的 `lint` job 由于文档内的格式问题而失败。在该 job 每次执行的输出中都包含可以直接应用以解决问题的 Git 补丁。

没事了 没事了，当时问你这个的时候是因为令牌没给权限。。。。
